# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staplestatter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(475, 496)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.processButton = QtWidgets.QPushButton(self.tab)
        self.processButton.setObjectName("processButton")
        self.verticalLayout_4.addWidget(self.processButton)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.browsePlotfileButton = QtWidgets.QPushButton(self.tab)
        self.browsePlotfileButton.setObjectName("browsePlotfileButton")
        self.horizontalLayout_2.addWidget(self.browsePlotfileButton)
        self.browseStatsfileButton = QtWidgets.QPushButton(self.tab)
        self.browseStatsfileButton.setObjectName("browseStatsfileButton")
        self.horizontalLayout_2.addWidget(self.browseStatsfileButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plotsfileLineEdit = QtWidgets.QLineEdit(self.tab)
        self.plotsfileLineEdit.setObjectName("plotsfileLineEdit")
        self.horizontalLayout_3.addWidget(self.plotsfileLineEdit)
        self.statsfileLineEdit = QtWidgets.QLineEdit(self.tab)
        self.statsfileLineEdit.setObjectName("statsfileLineEdit")
        self.horizontalLayout_3.addWidget(self.statsfileLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.processButton2 = QtWidgets.QPushButton(self.tab_2)
        self.processButton2.setObjectName("processButton2")
        self.verticalLayout.addWidget(self.processButton2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newSpecfileButton = QtWidgets.QPushButton(self.tab_2)
        self.newSpecfileButton.setObjectName("newSpecfileButton")
        self.horizontalLayout.addWidget(self.newSpecfileButton)
        self.loadSpecfileButton = QtWidgets.QPushButton(self.tab_2)
        self.loadSpecfileButton.setObjectName("loadSpecfileButton")
        self.horizontalLayout.addWidget(self.loadSpecfileButton)
        self.saveSpecfileAsButton = QtWidgets.QPushButton(self.tab_2)
        self.saveSpecfileAsButton.setObjectName("saveSpecfileAsButton")
        self.horizontalLayout.addWidget(self.saveSpecfileAsButton)
        self.saveSpecfileButton = QtWidgets.QPushButton(self.tab_2)
        self.saveSpecfileButton.setObjectName("saveSpecfileButton")
        self.horizontalLayout.addWidget(self.saveSpecfileButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.specfilepathLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.specfilepathLineEdit.setObjectName("specfilepathLineEdit")
        self.horizontalLayout_10.addWidget(self.specfilepathLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.specfileTextEdit = QtWidgets.QPlainTextEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.specfileTextEdit.setFont(font)
        self.specfileTextEdit.setObjectName("specfileTextEdit")
        self.verticalLayout.addWidget(self.specfileTextEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 433, 425))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.usageTextEdit = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.usageTextEdit.setObjectName("usageTextEdit")
        self.verticalLayout_6.addWidget(self.usageTextEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.processButton.setText(_translate("Dialog", "Process and plot!"))
        self.label_2.setText(_translate("Dialog", "Use the next tab to specify processing methods, then press \'Process\'."))
        self.label_3.setText(_translate("Dialog", "Save plot or stats/scores to file:"))
        self.browsePlotfileButton.setText(_translate("Dialog", "Save plot to file..."))
        self.browseStatsfileButton.setText(_translate("Dialog", "Save stats to file..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Control"))
        self.processButton2.setText(_translate("Dialog", "Process and plot!"))
        self.newSpecfileButton.setText(_translate("Dialog", "New..."))
        self.loadSpecfileButton.setText(_translate("Dialog", "Load..."))
        self.saveSpecfileAsButton.setText(_translate("Dialog", "Save As..."))
        self.saveSpecfileButton.setText(_translate("Dialog", "Save!"))
        self.label.setText(_translate("Dialog", "File: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Specify plots"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Usage help"))

