# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staplestatter.ui'
#
# Created: Sun May  4 23:58:25 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(391, 471)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.processButton = QtGui.QPushButton(self.tab)
        self.processButton.setObjectName(_fromUtf8("processButton"))
        self.verticalLayout_4.addWidget(self.processButton)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.plotsfileLineEdit = QtGui.QLineEdit(self.tab)
        self.plotsfileLineEdit.setObjectName(_fromUtf8("plotsfileLineEdit"))
        self.horizontalLayout_2.addWidget(self.plotsfileLineEdit)
        self.browsePlotfileButton = QtGui.QPushButton(self.tab)
        self.browsePlotfileButton.setObjectName(_fromUtf8("browsePlotfileButton"))
        self.horizontalLayout_2.addWidget(self.browsePlotfileButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.statsfileLineEdit = QtGui.QLineEdit(self.tab)
        self.statsfileLineEdit.setObjectName(_fromUtf8("statsfileLineEdit"))
        self.horizontalLayout_3.addWidget(self.statsfileLineEdit)
        self.browseStatsfileButton = QtGui.QPushButton(self.tab)
        self.browseStatsfileButton.setObjectName(_fromUtf8("browseStatsfileButton"))
        self.horizontalLayout_3.addWidget(self.browseStatsfileButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.loadSpecFileButton = QtGui.QPushButton(self.tab_2)
        self.loadSpecFileButton.setObjectName(_fromUtf8("loadSpecFileButton"))
        self.horizontalLayout.addWidget(self.loadSpecFileButton)
        self.saveSpecFileButton = QtGui.QPushButton(self.tab_2)
        self.saveSpecFileButton.setObjectName(_fromUtf8("saveSpecFileButton"))
        self.horizontalLayout.addWidget(self.saveSpecFileButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_10.addWidget(self.label)
        self.specFilepathLineEdit = QtGui.QLineEdit(self.tab_2)
        self.specFilepathLineEdit.setObjectName(_fromUtf8("specFilepathLineEdit"))
        self.horizontalLayout_10.addWidget(self.specFilepathLineEdit)
        self.browseSpecFileButton = QtGui.QPushButton(self.tab_2)
        self.browseSpecFileButton.setObjectName(_fromUtf8("browseSpecFileButton"))
        self.horizontalLayout_10.addWidget(self.browseSpecFileButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.specfileTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        self.specfileTextEdit.setFont(font)
        self.specfileTextEdit.setObjectName(_fromUtf8("specfileTextEdit"))
        self.verticalLayout.addWidget(self.specfileTextEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea = QtGui.QScrollArea(self.tab_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 349, 400))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.usageTextEdit = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.usageTextEdit.setUndoRedoEnabled(False)
        self.usageTextEdit.setReadOnly(True)
        self.usageTextEdit.setObjectName(_fromUtf8("usageTextEdit"))
        self.verticalLayout_6.addWidget(self.usageTextEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Use the next tab to specify processing methods, then press \'Process\'.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.processButton.setText(QtGui.QApplication.translate("Dialog", "Process and plot!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Save plot to file:", None, QtGui.QApplication.UnicodeUTF8))
        self.browsePlotfileButton.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Save stats data to file:", None, QtGui.QApplication.UnicodeUTF8))
        self.browseStatsfileButton.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSpecFileButton.setText(QtGui.QApplication.translate("Dialog", "Load spec from file", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSpecFileButton.setText(QtGui.QApplication.translate("Dialog", "Save this spec to file!", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "File: ", None, QtGui.QApplication.UnicodeUTF8))
        self.browseSpecFileButton.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Specify plots", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Usage help", None, QtGui.QApplication.UnicodeUTF8))

